"""turns y chat_history.session_id

Revision ID: 8df38d93ccd7
Revises: b77575dcdf9b
Create Date: 2026-08-27 03:17:00.309611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8df38d93ccd7'
down_revision: Union[str, Sequence[str], None] = 'b77575dcdf9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turn_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('step_before', sa.String(), nullable=True),
    sa.Column('step_after', sa.String(), nullable=True),
    sa.Column('decision', sa.JSON(), nullable=False),
    sa.Column('draft', sa.Text(), nullable=False),
    sa.Column('gate', sa.JSON(), nullable=False),
    sa.Column('bundle', sa.JSON(), nullable=False),
    sa.Column('tool', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'turn_id', name='uq_turns_session_id_turn_id')
    )
    with op.batch_alter_table('turns', schema=None) as batch_op:
        batch_op.create_index('ix_turns_session_id_created_at', ['session_id', 'created_at'], unique=False)

    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.String(), nullable=True))
        batch_op.create_index('ix_chat_history_user_id_session_id', ['user_id', 'session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.drop_index('ix_chat_history_user_id_session_id')
        batch_op.drop_column('session_id')

    with op.batch_alter_table('turns', schema=None) as batch_op:
        batch_op.drop_index('ix_turns_session_id_created_at')

    op.drop_table('turns')
    # ### end Alembic commands ###
