"""baseline: esquema actual

Revision ID: b77575dcdf9b
Revises: 
Create Date: 2026-08-27 01:25:04.811266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b77575dcdf9b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('chat_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', name='chat_history_role', native_enum=False), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('pii_scrubbed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.create_index('ix_chat_history_user_id_created_at', ['user_id', 'created_at'], unique=False)

    op.create_table('recordatorios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('dia', sa.String(), nullable=False),
    sa.Column('hora', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.String(), nullable=False),
    sa.Column('hora', sa.String(), nullable=False),
    sa.Column('personas', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_state',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_node', sa.Enum('IDLE', 'BUFFERING', 'EVALUATING_CONTEXT', 'DRAFTING_RESPONSE', 'WAITING_TOOL', 'BREAKPOINT_MISS', name='sessionnode', native_enum=False), nullable=False),
    sa.Column('active_domain', sa.String(), nullable=True),
    sa.Column('flow_node', sa.String(), nullable=True),
    sa.Column('flow_slots', sa.JSON(), nullable=True),
    sa.Column('buffer', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_traits',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trait_id', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_user_traits_confidence_between_0_and_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'trait_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_traits')
    op.drop_table('session_state')
    op.drop_table('reservas')
    op.drop_table('recordatorios')
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.drop_index('ix_chat_history_user_id_created_at')

    op.drop_table('chat_history')
    op.drop_table('users')
    # ### end Alembic commands ###
